# Generated by Django 3.0.3 on 2020-05-10 15:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactorPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_number', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
                ('ownership_status', models.CharField(choices=[('OK', 'GIVEN'), ('NOT OK', 'NOT GIVEN')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMEI', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('registration_status', models.CharField(choices=[('OWN', 'OWN'), ('POSTPONED', 'POSTPONED'), ('WHITE', 'WHITE'), ('NO', 'NO')], max_length=10)),
                ('guarantee_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('manufacturer', models.CharField(choices=[('China', 'China'), ('India', 'India'), ('Malaysia', 'Malaysia'), ('Vietnam', 'Vietnam'), ('United-State', 'United-State'), ('Hong-Kong', 'Hong-Kong')], max_length=15)),
                ('target_price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Target price (1000T)')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Customer')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
                ('test_result', models.CharField(choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED')], max_length=10)),
                ('test_description', models.TextField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('SOLD', 'SOLD')], default='AVAILABLE', max_length=10)),
                ('factor_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.FactorPaper')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Mobile')),
                ('purchase_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.PurchasePaper')),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.TestPaper')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ram', models.CharField(choices=[('1', '1GB'), ('1.5', '1.5GB'), ('1', '1GB'), ('2', '2GB'), ('3', '3GB'), ('4', '4GB'), ('6', '6GB'), ('8', '8GB'), ('12', '12GB')], max_length=5)),
                ('storage', models.CharField(choices=[('4', '4GB'), ('8', '8GB'), ('16', '16GB'), ('32', '32GB'), ('64', '64GB'), ('128', '128GB'), ('256', '256GB'), ('512', '512GB'), ('1028', '1T')], max_length=5)),
                ('attachments', models.CharField(choices=[('DUAL + SD CARD', 'DUAL + SD CARD'), ('HYBRID', 'HYBRID'), ('SINGLE + SD CARD', 'SINGLE + SD CARD'), ('SINGLE', 'SINGLE'), ('SD CARD', 'SD CARD'), ('NO SIM', 'NO SIM')], max_length=16)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Color')),
            ],
        ),
        migrations.AddField(
            model_name='mobile',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Model'),
        ),
        migrations.AddField(
            model_name='factorpaper',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Mobile'),
        ),
    ]
