# Generated by Django 3.0.3 on 2020-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20200510_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorpaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='purchasepaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
