# Generated by Django 3.0.3 on 2020-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20200510_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='registration_status',
            field=models.CharField(choices=[('OWN', 'OWN'), ('POSTPONED', 'POSTPONED'), ('WHITE', 'WHITE'), ('GUARANTEE CARD', 'GUARANTEE CARD')], max_length=15),
        ),
    ]
