# Generated by Django 3.0.3 on 2020-05-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20200510_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='price',
        ),
    ]
