# Generated by Django 3.0.3 on 2020-05-11 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobile', '0006_remove_testpaper_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUXJack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('length', models.CharField(choices=[('1m', '1m'), ('1.5m', '1.5m'), ('2m', '2m')], max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
            ],
        ),
        migrations.CreateModel(
            name='CarCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
            ],
        ),
        migrations.CreateModel(
            name='HandsFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('J Series', 'J Series')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
            ],
        ),
        migrations.CreateModel(
            name='MobileCable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[], max_length=20)),
                ('cable_type', models.CharField(choices=[('Normal Charging', 'Normal Charging'), ('Fast Charging', 'Fast Charging')], max_length=20)),
                ('length', models.CharField(choices=[('1m', '1m'), ('1.5m', '1.5m'), ('2m', '2m'), ('POWER BANK', 'POWER BANK')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
            ],
        ),
        migrations.CreateModel(
            name='MobileCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ampere', models.CharField(choices=[], max_length=4)),
                ('material', models.CharField(choices=[], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
            ],
        ),
        migrations.CreateModel(
            name='PowerBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('XIAOMI', 'XIAOMI'), ('SAMSUNG', 'SAMSUNG')], max_length=15)),
                ('capacity', models.CharField(choices=[('10000mA', '10000mA'), ('20000mA', '20000mA')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
            ],
        ),
        migrations.CreateModel(
            name='WirelessCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('SAMSUNG', 'SAMSUNG')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Model')),
            ],
        ),
        migrations.CreateModel(
            name='BackCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Price (1000T)')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Model')),
            ],
        ),
    ]
