# Generated by Django 3.0.3 on 2020-05-10 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('identification_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('address', models.TextField()),
            ],
        ),
    ]
